services:
  db:
    image: postgres:latest
    container_name: postgres_django
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pg_database_name
      POSTGRES_USER: pg_user   
      POSTGRES_PASSWORD: pg_password
    volumes: 
      - pg_data:/var/lib/postgresql/data
  
  web:
    build: .
    command: >
      sh -c "cd /code/srv && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    container_name: django_web
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:
    external: true